CREATE TABLE `TB_USER` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) DEFAULT NULL,
  `sex` TINYINT(1) DEFAULT 0,
  `account` VARCHAR(15) NOT NULL UNIQUE,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO TB_USER VALUES (NULL , '超级管理员', 0, 'admin', '123456');
INSERT INTO TB_USER VALUES (NULL ,'系统管理员', 1, 'system', '000124');